/*
 *
 *   UnicodeRewriter.java: GUI of ID3iconv which converts ID3 tags into Unicode 
 *   Copyright (C) 2004 ChiWai
 *
 *   This program is free software; you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation; either version 2 of the License, or
 *   (at your option) any later version.
 * 
 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *   GNU General Public License for more details.
 *
 *   You should have received a copy of the GNU General Public License
 *   along with this program; if not, write to the Free Software
 *   Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 */
package net.chiwai;
/*
 * UnicodeRewriter.java
 *
 * Created on June 13, 2004, 3:09 PM
 */
import java.io.File;

import javax.swing.JFileChooser;
import javax.swing.JFrame;

import net.iharder.dnd.FileDrop;
import net.zhoufeng.ID3iconv;

/**
 *
 * @author  huicw
 */
public class UnicodeRewriter extends JFrame {
    /** Creates new form UnicodeRewriter */
    public UnicodeRewriter() {
        initComponents();
        
        //Initialize variables
        initCustomizedVaraibles();
    }
    
    /** This method is called from within the constructor to
     * initialize the program.
     */
    private void initCustomizedVaraibles() {
        //Set Title
        setTitle ("Unicode Rewriter");

        version = "0.1";
        
        //Set Default Encoding
        Encoding.setText(System.getProperty("file.encoding"));

        //Reset sttatics
        nbFolder = 0;
        nbProcessed = 0;
        nbConverted = 0;

        //Use ID3iconv
        ID3Rewriter = new ID3iconv();


        //Allow drag and drop a file/folder to the folder list
        new FileDrop (DropPad, new FileDrop.Listener() {
            public void filesDropped (File[] files) {
                //Add file/folder to the folder list
                AddFolder (FolderList, files);

                //Enable "Convert" if there is folder in the list
                if (FolderList.getItemCount() != 0) {            
                    Convert.setEnabled(true);        
                }                        
            }
        });
                    
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        Browse = new javax.swing.JButton();
        Remove = new javax.swing.JButton();
        Encoding = new javax.swing.JTextField();
        RecursiveCheckBox = new javax.swing.JCheckBox();
        Convert = new javax.swing.JButton();
        Quit = new javax.swing.JButton();
        FolderList = new java.awt.List();
        EncodingLabel = new javax.swing.JLabel();
        StatusBar = new javax.swing.JLabel();
        DropPad = new javax.swing.JLabel();
        MenuBar = new javax.swing.JMenuBar();
        EncodingMenu = new javax.swing.JMenu();
        EastAsia = new javax.swing.JMenu();
        Chinese = new javax.swing.JMenu();
        Simplified = new javax.swing.JMenu();
        Cp935 = new javax.swing.JMenuItem();
        EUC_CN = new javax.swing.JMenuItem();
        GBK = new javax.swing.JMenuItem();
        ISO2022CN = new javax.swing.JMenuItem();
        ISO2022CN_GB = new javax.swing.JMenuItem();
        MS1381 = new javax.swing.JMenuItem();
        MS936 = new javax.swing.JMenuItem();
        Traditional = new javax.swing.JMenu();
        Big5 = new javax.swing.JMenuItem();
        Big5_HKSCS = new javax.swing.JMenuItem();
        Cp937 = new javax.swing.JMenuItem();
        Cp948 = new javax.swing.JMenuItem();
        Cp950 = new javax.swing.JMenuItem();
        Cp964 = new javax.swing.JMenuItem();
        EUC_TW = new javax.swing.JMenuItem();
        ISO2022CN_CNS = new javax.swing.JMenuItem();
        MS950 = new javax.swing.JMenuItem();
        Japanese = new javax.swing.JMenu();
        Cp33722 = new javax.swing.JMenuItem();
        Cp930 = new javax.swing.JMenuItem();
        Cp939 = new javax.swing.JMenuItem();
        Cp942 = new javax.swing.JMenuItem();
        Cp942C = new javax.swing.JMenuItem();
        Cp943 = new javax.swing.JMenuItem();
        Cp943C = new javax.swing.JMenuItem();
        EUC_JP = new javax.swing.JMenuItem();
        EUC_JP_LINUX = new javax.swing.JMenuItem();
        ISO2022JP = new javax.swing.JMenuItem();
        JIS0201 = new javax.swing.JMenuItem();
        JIS0208 = new javax.swing.JMenuItem();
        JIS0212 = new javax.swing.JMenuItem();
        JISAutoDetect = new javax.swing.JMenuItem();
        MS932 = new javax.swing.JMenuItem();
        SJIS = new javax.swing.JMenuItem();
        Korean = new javax.swing.JMenu();
        Cp933 = new javax.swing.JMenuItem();
        Cp949 = new javax.swing.JMenuItem();
        Cp949C = new javax.swing.JMenuItem();
        Cp970 = new javax.swing.JMenuItem();
        EUC_KR = new javax.swing.JMenuItem();
        Johab = new javax.swing.JMenuItem();
        MS949 = new javax.swing.JMenuItem();
        SESWAsia = new javax.swing.JMenu();
        Thai = new javax.swing.JMenu();
        Cp838 = new javax.swing.JMenuItem();
        Cp874 = new javax.swing.JMenuItem();
        MS874 = new javax.swing.JMenuItem();
        MacThai = new javax.swing.JMenuItem();
        TIS620 = new javax.swing.JMenuItem();
        Turkish = new javax.swing.JMenu();
        Cp1026 = new javax.swing.JMenuItem();
        Cp1254 = new javax.swing.JMenuItem();
        Cp857 = new javax.swing.JMenuItem();
        MacTurkish = new javax.swing.JMenuItem();
        Vietnamese = new javax.swing.JMenu();
        Cp1258 = new javax.swing.JMenuItem();
        EEurope = new javax.swing.JMenu();
        Baltic = new javax.swing.JMenu();
        Cp71257 = new javax.swing.JMenuItem();
        Cp775 = new javax.swing.JMenuItem();
        CEuropean = new javax.swing.JMenu();
        Cp852 = new javax.swing.JMenuItem();
        MacCentral = new javax.swing.JMenuItem();
        Cyrillic = new javax.swing.JMenu();
        Cp1251 = new javax.swing.JMenuItem();
        Cp855 = new javax.swing.JMenuItem();
        ISO8859_5 = new javax.swing.JMenuItem();
        MacCyrillic = new javax.swing.JMenuItem();
        EEuropean = new javax.swing.JMenu();
        Cp1250 = new javax.swing.JMenuItem();
        Romania = new javax.swing.JMenu();
        MacRomania = new javax.swing.JMenuItem();
        Russian = new javax.swing.JMenu();
        Cp866 = new javax.swing.JMenuItem();
        KOI8_R = new javax.swing.JMenuItem();
        Ukraine = new javax.swing.JMenu();
        Cp1123 = new javax.swing.JMenuItem();
        Cp1124 = new javax.swing.JMenuItem();
        MacUkraine = new javax.swing.JMenuItem();
        WEurope = new javax.swing.JMenu();
        Greek = new javax.swing.JMenu();
        Cp1253 = new javax.swing.JMenuItem();
        Cp737 = new javax.swing.JMenuItem();
        Cp869 = new javax.swing.JMenuItem();
        Cp875 = new javax.swing.JMenuItem();
        ISO8859_7 = new javax.swing.JMenuItem();
        MacGreek = new javax.swing.JMenuItem();
        Icelandic = new javax.swing.JMenu();
        Cp861 = new javax.swing.JMenuItem();
        Cp871 = new javax.swing.JMenuItem();
        MacIceland = new javax.swing.JMenuItem();
        Nordic = new javax.swing.JMenu();
        Cp865 = new javax.swing.JMenuItem();
        Roman = new javax.swing.JMenu();
        MacRoman = new javax.swing.JMenuItem();
        MiddleEast = new javax.swing.JMenu();
        Arabic = new javax.swing.JMenu();
        Cp1046 = new javax.swing.JMenuItem();
        Cp1256 = new javax.swing.JMenuItem();
        Cp420 = new javax.swing.JMenuItem();
        Cp864 = new javax.swing.JMenuItem();
        ISO8859_6 = new javax.swing.JMenuItem();
        MacArabic = new javax.swing.JMenuItem();
        Farsi = new javax.swing.JMenu();
        Cp1097 = new javax.swing.JMenuItem();
        Cp1098 = new javax.swing.JMenuItem();
        Hebrew = new javax.swing.JMenu();
        Cp1255 = new javax.swing.JMenuItem();
        Cp424 = new javax.swing.JMenuItem();
        Cp856 = new javax.swing.JMenuItem();
        Cp862 = new javax.swing.JMenuItem();
        ISO8859_8 = new javax.swing.JMenuItem();
        MacHebrew = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JSeparator();
        Default = new javax.swing.JMenuItem();
        AboutMenu = new javax.swing.JMenu();
        AboutItem = new javax.swing.JMenuItem();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        Browse.setMnemonic('B');
        Browse.setText("Browse");
        Browse.setToolTipText("Browse to select a folder");
        Browse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BrowseActionPerformed(evt);
            }
        });

        getContentPane().add(Browse, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, -1, -1));

        Remove.setMnemonic('R');
        Remove.setText("Remove");
        Remove.setToolTipText("Remove folder from the list");
        Remove.setEnabled(false);
        Remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveActionPerformed(evt);
            }
        });

        getContentPane().add(Remove, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, -1, -1));

        Encoding.setText("System Encoding");
        Encoding.setToolTipText("Please choose encoding from the menu or type directly");
        getContentPane().add(Encoding, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 100, -1));

        RecursiveCheckBox.setMnemonic('u');
        RecursiveCheckBox.setSelected(true);
        RecursiveCheckBox.setText("Recursive");
        RecursiveCheckBox.setToolTipText("Convert files in the folder recursively");
        RecursiveCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RecursiveCheckBoxActionPerformed(evt);
            }
        });

        getContentPane().add(RecursiveCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, -1, -1));

        Convert.setMnemonic('C');
        Convert.setText("Convert");
        Convert.setToolTipText("Convert the MP3 files in the list");
        Convert.setEnabled(false);
        Convert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConvertActionPerformed(evt);
            }
        });

        getContentPane().add(Convert, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        Quit.setMnemonic('Q');
        Quit.setText("Quit");
        Quit.setToolTipText("Exit");
        Quit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuitActionPerformed(evt);
            }
        });

        getContentPane().add(Quit, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, -1, -1));

        FolderList.setMultipleMode(true);
        FolderList.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                FolderListItemStateChanged(evt);
            }
        });

        getContentPane().add(FolderList, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 250, 170));

        EncodingLabel.setLabelFor(Encoding);
        EncodingLabel.setText("Source Encoding");
        EncodingLabel.setFocusable(false);
        getContentPane().add(EncodingLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        StatusBar.setText("Ready");
        StatusBar.setToolTipText("Please see console for details");
        StatusBar.setBorder(new javax.swing.border.EtchedBorder());
        StatusBar.setFocusable(false);
        getContentPane().add(StatusBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 400, -1));

        DropPad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DropPad.setText("Drop here");
        DropPad.setFocusable(false);
        DropPad.setEnabled(false);
        getContentPane().add(DropPad, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        EncodingMenu.setMnemonic('E');
        EncodingMenu.setText("Encoding");
        EastAsia.setMnemonic('A');
        EastAsia.setText("East Asia");
        Chinese.setMnemonic('C');
        Chinese.setText("Chinese");
        Simplified.setMnemonic('S');
        Simplified.setText("Simplified");
        Cp935.setText("Cp935");
        Cp935.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cp935ActionPerformed(evt);
            }
        });

        Simplified.add(Cp935);

        EUC_CN.setText("EUC_CN");
        EUC_CN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EUC_CNActionPerformed(evt);
            }
        });

        Simplified.add(EUC_CN);

        GBK.setText("GBK");
        GBK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GBKActionPerformed(evt);
            }
        });

        Simplified.add(GBK);

        ISO2022CN.setText("ISO2022CN");
        ISO2022CN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ISO2022CNActionPerformed(evt);
            }
        });

        Simplified.add(ISO2022CN);

        ISO2022CN_GB.setText("ISO2022CN_GB");
        ISO2022CN_GB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ISO2022CN_GBActionPerformed(evt);
            }
        });

        Simplified.add(ISO2022CN_GB);

        MS1381.setText("MS1381");
        MS1381.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MS1381ActionPerformed(evt);
            }
        });

        Simplified.add(MS1381);

        MS936.setText("MS936");
        MS936.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MS936ActionPerformed(evt);
            }
        });

        Simplified.add(MS936);

        Chinese.add(Simplified);

        Traditional.setMnemonic('T');
        Traditional.setText("Traditional");
        Big5.setText("Big5");
        Big5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Big5ActionPerformed(evt);
            }
        });

        Traditional.add(Big5);

        Big5_HKSCS.setText("Big5_HKSCS");
        Big5_HKSCS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Big5_HKSCSActionPerformed(evt);
            }
        });

        Traditional.add(Big5_HKSCS);

        Cp937.setText("Cp937");
        Cp937.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cp937ActionPerformed(evt);
            }
        });

        Traditional.add(Cp937);

        Cp948.setText("Cp948");
        Cp948.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cp948ActionPerformed(evt);
            }
        });

        Traditional.add(Cp948);

        Cp950.setText("Cp950");
        Cp950.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cp950ActionPerformed(evt);
            }
        });

        Traditional.add(Cp950);

        Cp964.setText("Cp964");
        Cp964.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cp964ActionPerformed(evt);
            }
        });

        Traditional.add(Cp964);

        EUC_TW.setText("EUC_TW");
        EUC_TW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EUC_TWActionPerformed(evt);
            }
        });

        Traditional.add(EUC_TW);

        ISO2022CN_CNS.setText("ISO2022CN_CNS");
        ISO2022CN_CNS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ISO2022CN_CNSActionPerformed(evt);
            }
        });

        Traditional.add(ISO2022CN_CNS);

        MS950.setText("MS950");
        MS950.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MS950ActionPerformed(evt);
            }
        });

        Traditional.add(MS950);

        Chinese.add(Traditional);

        EastAsia.add(Chinese);

        Japanese.setMnemonic('J');
        Japanese.setText("Japanese");
        Cp33722.setText("Cp33722");
        Cp33722.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cp33722ActionPerformed(evt);
            }
        });

        Japanese.add(Cp33722);

        Cp930.setText("Cp930");
        Cp930.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cp930ActionPerformed(evt);
            }
        });

        Japanese.add(Cp930);

        Cp939.setText("Cp939");
        Cp939.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cp939ActionPerformed(evt);
            }
        });

        Japanese.add(Cp939);

        Cp942.setText("Cp942");
        Cp942.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cp942ActionPerformed(evt);
            }
        });

        Japanese.add(Cp942);

        Cp942C.setText("Cp942C");
        Cp942C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cp942CActionPerformed(evt);
            }
        });

        Japanese.add(Cp942C);

        Cp943.setText("Cp943");
        Cp943.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cp943ActionPerformed(evt);
            }
        });

        Japanese.add(Cp943);

        Cp943C.setText("Cp943C");
        Cp943C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cp943CActionPerformed(evt);
            }
        });

        Japanese.add(Cp943C);

        EUC_JP.setText("EUC_JP");
        EUC_JP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EUC_JPActionPerformed(evt);
            }
        });

        Japanese.add(EUC_JP);

        EUC_JP_LINUX.setText("EUC_JP_LINUX");
        EUC_JP_LINUX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EUC_JP_LINUXActionPerformed(evt);
            }
        });

        Japanese.add(EUC_JP_LINUX);

        ISO2022JP.setText("ISO2022JP");
        ISO2022JP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ISO2022JPActionPerformed(evt);
            }
        });

        Japanese.add(ISO2022JP);

        JIS0201.setText("JIS0201");
        JIS0201.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JIS0201ActionPerformed(evt);
            }
        });

        Japanese.add(JIS0201);

        JIS0208.setText("JIS0208");
        JIS0208.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JIS0208ActionPerformed(evt);
            }
        });

        Japanese.add(JIS0208);

        JIS0212.setText("JIS0212");
        JIS0212.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JIS0212ActionPerformed(evt);
            }
        });

        Japanese.add(JIS0212);

        JISAutoDetect.setText("JISAutoDetect");
        JISAutoDetect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JISAutoDetectActionPerformed(evt);
            }
        });

        Japanese.add(JISAutoDetect);

        MS932.setText("MS932");
        MS932.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MS932ActionPerformed(evt);
            }
        });

        Japanese.add(MS932);

        SJIS.setText("SJIS");
        SJIS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SJISActionPerformed(evt);
            }
        });

        Japanese.add(SJIS);

        EastAsia.add(Japanese);

        Korean.setMnemonic('K');
        Korean.setText("Korean");
        Cp933.setText("Cp933");
        Cp933.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cp933ActionPerformed(evt);
            }
        });

        Korean.add(Cp933);

        Cp949.setText("Cp949");
        Cp949.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cp949ActionPerformed(evt);
            }
        });

        Korean.add(Cp949);

        Cp949C.setText("Cp949C");
        Cp949C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cp949CActionPerformed(evt);
            }
        });

        Korean.add(Cp949C);

        Cp970.setText("Cp970");
        Cp970.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cp970ActionPerformed(evt);
            }
        });

        Korean.add(Cp970);

        EUC_KR.setText("EUC_KR");
        EUC_KR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EUC_KRActionPerformed(evt);
            }
        });

        Korean.add(EUC_KR);

        Johab.setText("Johab");
        Johab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JohabActionPerformed(evt);
            }
        });

        Korean.add(Johab);

        MS949.setText("MS949");
        MS949.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MS949ActionPerformed(evt);
            }
        });

        Korean.add(MS949);

        EastAsia.add(Korean);

        EncodingMenu.add(EastAsia);

        SESWAsia.setMnemonic('S');
        SESWAsia.setText("SE & SW Asia");
        Thai.setMnemonic('T');
        Thai.setText("Thai");
        Cp838.setText("Cp838");
        Cp838.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cp838ActionPerformed(evt);
            }
        });

        Thai.add(Cp838);

        Cp874.setText("Cp874");
        Cp874.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cp874ActionPerformed(evt);
            }
        });

        Thai.add(Cp874);

        MS874.setText("Cp874");
        MS874.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MS874ActionPerformed(evt);
            }
        });

        Thai.add(MS874);

        MacThai.setText("MacThai");
        MacThai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MacThaiActionPerformed(evt);
            }
        });

        Thai.add(MacThai);

        TIS620.setText("TIS620");
        TIS620.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TIS620ActionPerformed(evt);
            }
        });

        Thai.add(TIS620);

        SESWAsia.add(Thai);

        Turkish.setMnemonic('u');
        Turkish.setText("Turkish");
        Cp1026.setText("Cp1026");
        Cp1026.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cp1026ActionPerformed(evt);
            }
        });

        Turkish.add(Cp1026);

        Cp1254.setText("Cp1254");
        Cp1254.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cp1254ActionPerformed(evt);
            }
        });

        Turkish.add(Cp1254);

        Cp857.setText("Cp857");
        Cp857.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cp857ActionPerformed(evt);
            }
        });

        Turkish.add(Cp857);

        MacTurkish.setText("MacTurkish");
        MacTurkish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MacTurkishActionPerformed(evt);
            }
        });

        Turkish.add(MacTurkish);

        SESWAsia.add(Turkish);

        Vietnamese.setMnemonic('V');
        Vietnamese.setText("Vietnamese");
        Cp1258.setText("Cp1258");
        Cp1258.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cp1258ActionPerformed(evt);
            }
        });

        Vietnamese.add(Cp1258);

        SESWAsia.add(Vietnamese);

        EncodingMenu.add(SESWAsia);

        EEurope.setMnemonic('E');
        EEurope.setText("East European");
        Baltic.setMnemonic('B');
        Baltic.setText("Baltic");
        Cp71257.setText("Cp71257");
        Cp71257.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cp71257ActionPerformed(evt);
            }
        });

        Baltic.add(Cp71257);

        Cp775.setText("Cp775");
        Cp775.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cp775ActionPerformed(evt);
            }
        });

        Baltic.add(Cp775);

        EEurope.add(Baltic);

        CEuropean.setMnemonic('E');
        CEuropean.setText("Central European");
        Cp852.setText("Cp852");
        Cp852.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cp852ActionPerformed(evt);
            }
        });

        CEuropean.add(Cp852);

        MacCentral.setText("MacCentral");
        MacCentral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MacCentralActionPerformed(evt);
            }
        });

        CEuropean.add(MacCentral);

        EEurope.add(CEuropean);

        Cyrillic.setMnemonic('C');
        Cyrillic.setText("Cyrillic");
        Cp1251.setText("Cp1251");
        Cp1251.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cp1251ActionPerformed(evt);
            }
        });

        Cyrillic.add(Cp1251);

        Cp855.setText("Cp855");
        Cp855.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cp855ActionPerformed(evt);
            }
        });

        Cyrillic.add(Cp855);

        ISO8859_5.setText("ISO8859_5");
        ISO8859_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ISO8859_5ActionPerformed(evt);
            }
        });

        Cyrillic.add(ISO8859_5);

        MacCyrillic.setText("MacCyrillic");
        MacCyrillic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MacCyrillicActionPerformed(evt);
            }
        });

        Cyrillic.add(MacCyrillic);

        EEurope.add(Cyrillic);

        EEuropean.setMnemonic('o');
        EEuropean.setText("East European");
        Cp1250.setText("Cp1250");
        Cp1250.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cp1250ActionPerformed(evt);
            }
        });

        EEuropean.add(Cp1250);

        EEurope.add(EEuropean);

        Romania.setMnemonic('R');
        Romania.setText("Romania");
        MacRomania.setText("MacRomania");
        MacRomania.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MacRomaniaActionPerformed(evt);
            }
        });

        Romania.add(MacRomania);

        EEurope.add(Romania);

        Russian.setMnemonic('s');
        Russian.setText("Russian");
        Cp866.setText("Cp866");
        Cp866.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cp866ActionPerformed(evt);
            }
        });

        Russian.add(Cp866);

        KOI8_R.setText("KOI8_R");
        KOI8_R.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KOI8_RActionPerformed(evt);
            }
        });

        Russian.add(KOI8_R);

        EEurope.add(Russian);

        Ukraine.setMnemonic('U');
        Ukraine.setText("Ukraine");
        Cp1123.setText("Cp1123");
        Cp1123.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cp1123ActionPerformed(evt);
            }
        });

        Ukraine.add(Cp1123);

        Cp1124.setText("Cp1124");
        Cp1124.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cp1124ActionPerformed(evt);
            }
        });

        Ukraine.add(Cp1124);

        MacUkraine.setText("MacUkraine");
        MacUkraine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MacUkraineActionPerformed(evt);
            }
        });

        Ukraine.add(MacUkraine);

        EEurope.add(Ukraine);

        EncodingMenu.add(EEurope);

        WEurope.setMnemonic('W');
        WEurope.setText("West European");
        Greek.setMnemonic('G');
        Greek.setText("Greek");
        Cp1253.setText("Cp1253");
        Cp1253.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cp1253ActionPerformed(evt);
            }
        });

        Greek.add(Cp1253);

        Cp737.setText("Cp737");
        Cp737.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cp737ActionPerformed(evt);
            }
        });

        Greek.add(Cp737);

        Cp869.setText("Cp869");
        Cp869.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cp869ActionPerformed(evt);
            }
        });

        Greek.add(Cp869);

        Cp875.setText("Cp875");
        Cp875.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cp875ActionPerformed(evt);
            }
        });

        Greek.add(Cp875);

        ISO8859_7.setText("ISO8859_7");
        ISO8859_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ISO8859_7ActionPerformed(evt);
            }
        });

        Greek.add(ISO8859_7);

        MacGreek.setText("MacGreek");
        MacGreek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MacGreekActionPerformed(evt);
            }
        });

        Greek.add(MacGreek);

        WEurope.add(Greek);

        Icelandic.setMnemonic('I');
        Icelandic.setText("Icelandic");
        Cp861.setText("Cp861");
        Cp861.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cp861ActionPerformed(evt);
            }
        });

        Icelandic.add(Cp861);

        Cp871.setText("Cp871");
        Cp871.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cp871ActionPerformed(evt);
            }
        });

        Icelandic.add(Cp871);

        MacIceland.setText("MacIceland");
        MacIceland.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MacIcelandActionPerformed(evt);
            }
        });

        Icelandic.add(MacIceland);

        WEurope.add(Icelandic);

        Nordic.setMnemonic('N');
        Nordic.setText("Nordic");
        Cp865.setText("Cp865");
        Cp865.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cp865ActionPerformed(evt);
            }
        });

        Nordic.add(Cp865);

        WEurope.add(Nordic);

        Roman.setMnemonic('R');
        Roman.setText("Roman");
        MacRoman.setText("MacRoman");
        MacRoman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MacRomanActionPerformed(evt);
            }
        });

        Roman.add(MacRoman);

        WEurope.add(Roman);

        EncodingMenu.add(WEurope);

        MiddleEast.setMnemonic('M');
        MiddleEast.setText("Middle East");
        Arabic.setMnemonic('A');
        Arabic.setText("Arabic");
        Cp1046.setText("Cp1046");
        Cp1046.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cp1046ActionPerformed(evt);
            }
        });

        Arabic.add(Cp1046);

        Cp1256.setText("Cp1256");
        Cp1256.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cp1256ActionPerformed(evt);
            }
        });

        Arabic.add(Cp1256);

        Cp420.setText("Cp420");
        Cp420.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cp420ActionPerformed(evt);
            }
        });

        Arabic.add(Cp420);

        Cp864.setText("Cp864");
        Cp864.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cp864ActionPerformed(evt);
            }
        });

        Arabic.add(Cp864);

        ISO8859_6.setText("ISO8859_6");
        ISO8859_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ISO8859_6ActionPerformed(evt);
            }
        });

        Arabic.add(ISO8859_6);

        MacArabic.setText("MacArabic");
        MacArabic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MacArabicActionPerformed(evt);
            }
        });

        Arabic.add(MacArabic);

        MiddleEast.add(Arabic);

        Farsi.setMnemonic('F');
        Farsi.setText("Farsi");
        Cp1097.setText("Cp1097");
        Cp1097.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cp1097ActionPerformed(evt);
            }
        });

        Farsi.add(Cp1097);

        Cp1098.setText("Cp1098");
        Cp1098.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cp1098ActionPerformed(evt);
            }
        });

        Farsi.add(Cp1098);

        MiddleEast.add(Farsi);

        Hebrew.setMnemonic('H');
        Hebrew.setText("Hebrew");
        Cp1255.setText("Cp1255");
        Cp1255.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cp1255ActionPerformed(evt);
            }
        });

        Hebrew.add(Cp1255);

        Cp424.setText("Cp424");
        Cp424.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cp424ActionPerformed(evt);
            }
        });

        Hebrew.add(Cp424);

        Cp856.setText("Cp856");
        Cp856.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cp856ActionPerformed(evt);
            }
        });

        Hebrew.add(Cp856);

        Cp862.setText("Cp862");
        Cp862.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cp862ActionPerformed(evt);
            }
        });

        Hebrew.add(Cp862);

        ISO8859_8.setText("ISO8859_8");
        ISO8859_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ISO8859_8ActionPerformed(evt);
            }
        });

        Hebrew.add(ISO8859_8);

        MacHebrew.setText("MacHebrew");
        MacHebrew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MacHebrewActionPerformed(evt);
            }
        });

        Hebrew.add(MacHebrew);

        MiddleEast.add(Hebrew);

        EncodingMenu.add(MiddleEast);

        EncodingMenu.add(jSeparator1);

        Default.setMnemonic('D');
        Default.setText("Default");
        Default.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DefaultActionPerformed(evt);
            }
        });

        EncodingMenu.add(Default);

        MenuBar.add(EncodingMenu);

        AboutMenu.setMnemonic('A');
        AboutMenu.setText("About");
        AboutItem.setMnemonic('A');
        AboutItem.setText("About Unicode Rewriter");
        AboutItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AboutItemActionPerformed(evt);
            }
        });

        AboutMenu.add(AboutItem);

        MenuBar.add(AboutMenu);

        setJMenuBar(MenuBar);

        pack();
    }//GEN-END:initComponents

    private void Cp1046ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cp1046ActionPerformed
        // Add your handling code here:
        Encoding.setText ("Cp1046");
    }//GEN-LAST:event_Cp1046ActionPerformed

    private void Cp1256ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cp1256ActionPerformed
        // Add your handling code here:
        Encoding.setText ("Cp1256");
    }//GEN-LAST:event_Cp1256ActionPerformed

    private void Cp420ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cp420ActionPerformed
        // Add your handling code here:
        Encoding.setText ("Cp420");
    }//GEN-LAST:event_Cp420ActionPerformed

    private void Cp864ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cp864ActionPerformed
        // Add your handling code here:
        Encoding.setText ("Cp864");
    }//GEN-LAST:event_Cp864ActionPerformed

    private void ISO8859_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ISO8859_6ActionPerformed
        // Add your handling code here:
        Encoding.setText ("ISO8859_6");
    }//GEN-LAST:event_ISO8859_6ActionPerformed

    private void MacArabicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MacArabicActionPerformed
        // Add your handling code here:
        Encoding.setText ("MacArabic");
    }//GEN-LAST:event_MacArabicActionPerformed

    private void Cp1097ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cp1097ActionPerformed
        // Add your handling code here:
        Encoding.setText ("Cp1097");
    }//GEN-LAST:event_Cp1097ActionPerformed

    private void Cp1098ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cp1098ActionPerformed
        // Add your handling code here:
        Encoding.setText ("Cp1098");
    }//GEN-LAST:event_Cp1098ActionPerformed

    private void Cp1255ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cp1255ActionPerformed
        // Add your handling code here:
        Encoding.setText ("Cp1255");
    }//GEN-LAST:event_Cp1255ActionPerformed

    private void Cp424ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cp424ActionPerformed
        // Add your handling code here:
        Encoding.setText ("Cp424");
    }//GEN-LAST:event_Cp424ActionPerformed

    private void Cp856ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cp856ActionPerformed
        // Add your handling code here:
        Encoding.setText ("Cp856");
    }//GEN-LAST:event_Cp856ActionPerformed

    private void Cp862ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cp862ActionPerformed
        // Add your handling code here:
        Encoding.setText ("Cp862");
    }//GEN-LAST:event_Cp862ActionPerformed

    private void ISO8859_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ISO8859_8ActionPerformed
        // Add your handling code here:
        Encoding.setText ("ISO8859_8");
    }//GEN-LAST:event_ISO8859_8ActionPerformed

    private void MacHebrewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MacHebrewActionPerformed
        // Add your handling code here:
        Encoding.setText ("MacHebrew");
    }//GEN-LAST:event_MacHebrewActionPerformed

    private void Cp865ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cp865ActionPerformed
        // Add your handling code here:
        Encoding.setText ("Cp865");
    }//GEN-LAST:event_Cp865ActionPerformed

    private void MacRomanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MacRomanActionPerformed
        // Add your handling code here:
        Encoding.setText ("MacRoman");
    }//GEN-LAST:event_MacRomanActionPerformed

    private void MacIcelandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MacIcelandActionPerformed
        // Add your handling code here:
        Encoding.setText ("MacIceland");
    }//GEN-LAST:event_MacIcelandActionPerformed

    private void Cp871ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cp871ActionPerformed
        // Add your handling code here:
        Encoding.setText ("Cp871");
    }//GEN-LAST:event_Cp871ActionPerformed

    private void Cp861ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cp861ActionPerformed
        // Add your handling code here:
        Encoding.setText ("Cp861");
    }//GEN-LAST:event_Cp861ActionPerformed

    private void MacGreekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MacGreekActionPerformed
        // Add your handling code here:
        Encoding.setText ("MacGreek");
    }//GEN-LAST:event_MacGreekActionPerformed

    private void ISO8859_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ISO8859_7ActionPerformed
        // Add your handling code here:
        Encoding.setText ("ISO8859_7");
    }//GEN-LAST:event_ISO8859_7ActionPerformed

    private void Cp875ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cp875ActionPerformed
        // Add your handling code here:
        Encoding.setText ("Cp875");
    }//GEN-LAST:event_Cp875ActionPerformed

    private void Cp869ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cp869ActionPerformed
        // Add your handling code here:
        Encoding.setText ("Cp869");
    }//GEN-LAST:event_Cp869ActionPerformed

    private void Cp737ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cp737ActionPerformed
        // Add your handling code here:
        Encoding.setText ("Cp737");
    }//GEN-LAST:event_Cp737ActionPerformed

    private void Cp1253ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cp1253ActionPerformed
        // Add your handling code here:
        Encoding.setText ("Cp1253");
    }//GEN-LAST:event_Cp1253ActionPerformed

    private void Cp71257ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cp71257ActionPerformed
        // Add your handling code here:
        Encoding.setText ("Cp71257");   
    }//GEN-LAST:event_Cp71257ActionPerformed

    private void Cp775ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cp775ActionPerformed
        // Add your handling code here:
        Encoding.setText ("Cp775");   
    }//GEN-LAST:event_Cp775ActionPerformed

    private void Cp852ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cp852ActionPerformed
        // Add your handling code here:
        Encoding.setText ("Cp852");   
    }//GEN-LAST:event_Cp852ActionPerformed

    private void MacCentralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MacCentralActionPerformed
        // Add your handling code here:
        Encoding.setText ("MacCentral");   
    }//GEN-LAST:event_MacCentralActionPerformed

    private void Cp1251ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cp1251ActionPerformed
        // Add your handling code here:
        Encoding.setText ("Cp1251");   
    }//GEN-LAST:event_Cp1251ActionPerformed

    private void Cp855ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cp855ActionPerformed
        // Add your handling code here:
        Encoding.setText ("Cp855");   
    }//GEN-LAST:event_Cp855ActionPerformed

    private void ISO8859_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ISO8859_5ActionPerformed
        // Add your handling code here:
        Encoding.setText ("ISO8859_5");   
    }//GEN-LAST:event_ISO8859_5ActionPerformed

    private void MacCyrillicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MacCyrillicActionPerformed
        // Add your handling code here:
        Encoding.setText ("MacCyrillic");   
    }//GEN-LAST:event_MacCyrillicActionPerformed

    private void Cp1250ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cp1250ActionPerformed
        // Add your handling code here:
        Encoding.setText ("Cp1250");   
    }//GEN-LAST:event_Cp1250ActionPerformed

    private void MacRomaniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MacRomaniaActionPerformed
        // Add your handling code here:
        Encoding.setText ("MacRomania");   
    }//GEN-LAST:event_MacRomaniaActionPerformed

    private void Cp866ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cp866ActionPerformed
        // Add your handling code here:
        Encoding.setText ("Cp866");   
    }//GEN-LAST:event_Cp866ActionPerformed

    private void KOI8_RActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KOI8_RActionPerformed
        // Add your handling code here:
        Encoding.setText ("KOI8_R");   
    }//GEN-LAST:event_KOI8_RActionPerformed

    private void Cp1123ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cp1123ActionPerformed
        // Add your handling code here:
        Encoding.setText ("Cp1123");   
    }//GEN-LAST:event_Cp1123ActionPerformed

    private void Cp1124ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cp1124ActionPerformed
        // Add your handling code here:
        Encoding.setText ("Cp1124");   
    }//GEN-LAST:event_Cp1124ActionPerformed

    private void MacUkraineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MacUkraineActionPerformed
        // Add your handling code here:
        Encoding.setText ("MacUkraine");   
    }//GEN-LAST:event_MacUkraineActionPerformed

    private void RecursiveCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RecursiveCheckBoxActionPerformed
        // Add your handling code here:                   
        //Update status bar
        if (RecursiveCheckBox.isSelected()) {
            StatusBar.setText ("Folders will be recursively visited.");
        } else {
            StatusBar.setText ("Folders will NOT be recursively visited.");
        }
    }//GEN-LAST:event_RecursiveCheckBoxActionPerformed

    private void Cp1258ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cp1258ActionPerformed
        // Add your handling code here:
        Encoding.setText ("Cp1258"); 
    }//GEN-LAST:event_Cp1258ActionPerformed

    private void MacTurkishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MacTurkishActionPerformed
        // Add your handling code here:
        Encoding.setText ("MacTurkish"); 
    }//GEN-LAST:event_MacTurkishActionPerformed

    private void Cp857ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cp857ActionPerformed
        // Add your handling code here:
        Encoding.setText ("Cp857"); 
    }//GEN-LAST:event_Cp857ActionPerformed

    private void Cp1254ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cp1254ActionPerformed
        // Add your handling code here:
        Encoding.setText ("Cp1254"); 
    }//GEN-LAST:event_Cp1254ActionPerformed

    private void Cp1026ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cp1026ActionPerformed
        // Add your handling code here:
        Encoding.setText ("Cp1026"); 
    }//GEN-LAST:event_Cp1026ActionPerformed

    private void TIS620ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TIS620ActionPerformed
        // Add your handling code here:
        Encoding.setText ("TIS620"); 
    }//GEN-LAST:event_TIS620ActionPerformed

    private void MacThaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MacThaiActionPerformed
        // Add your handling code here:
        Encoding.setText ("MacThai"); 
    }//GEN-LAST:event_MacThaiActionPerformed

    private void MS874ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MS874ActionPerformed
        // Add your handling code here:
        Encoding.setText ("MS874"); 
    }//GEN-LAST:event_MS874ActionPerformed

    private void Cp874ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cp874ActionPerformed
        // Add your handling code here:
        Encoding.setText ("Cp874"); 
    }//GEN-LAST:event_Cp874ActionPerformed

    private void Cp838ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cp838ActionPerformed
        // Add your handling code here:
        Encoding.setText ("Cp838"); 
    }//GEN-LAST:event_Cp838ActionPerformed

    private void MS949ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MS949ActionPerformed
        // Add your handling code here:
        Encoding.setText ("MS949");        
    }//GEN-LAST:event_MS949ActionPerformed

    private void JohabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JohabActionPerformed
        // Add your handling code here:
        Encoding.setText ("Johab");        
    }//GEN-LAST:event_JohabActionPerformed

    private void EUC_KRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EUC_KRActionPerformed
        // Add your handling code here:
        Encoding.setText ("EUC_KR");        
    }//GEN-LAST:event_EUC_KRActionPerformed

    private void Cp970ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cp970ActionPerformed
        // Add your handling code here:
        Encoding.setText ("Cp970");        
    }//GEN-LAST:event_Cp970ActionPerformed

    private void Cp949CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cp949CActionPerformed
        // Add your handling code here:
        Encoding.setText ("Cp949C");        
    }//GEN-LAST:event_Cp949CActionPerformed

    private void Cp949ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cp949ActionPerformed
        // Add your handling code here:
        Encoding.setText ("Cp949");        
    }//GEN-LAST:event_Cp949ActionPerformed

    private void Cp933ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cp933ActionPerformed
        // Add your handling code here:
        Encoding.setText ("Cp933");        
    }//GEN-LAST:event_Cp933ActionPerformed

    private void SJISActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SJISActionPerformed
        // Add your handling code here:
        Encoding.setText ("SJIS");        
    }//GEN-LAST:event_SJISActionPerformed

    private void MS932ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MS932ActionPerformed
        // Add your handling code here:
        Encoding.setText ("MS932");        
    }//GEN-LAST:event_MS932ActionPerformed

    private void JISAutoDetectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JISAutoDetectActionPerformed
        // Add your handling code here:
        Encoding.setText ("JISAutoDetect");        
    }//GEN-LAST:event_JISAutoDetectActionPerformed

    private void JIS0212ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JIS0212ActionPerformed
        // Add your handling code here:
        Encoding.setText ("JIS0212");        
    }//GEN-LAST:event_JIS0212ActionPerformed

    private void JIS0208ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JIS0208ActionPerformed
        // Add your handling code here:
        Encoding.setText ("JIS0208");        
    }//GEN-LAST:event_JIS0208ActionPerformed

    private void JIS0201ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JIS0201ActionPerformed
        // Add your handling code here:
        Encoding.setText ("JIS0201");        
    }//GEN-LAST:event_JIS0201ActionPerformed

    private void ISO2022JPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ISO2022JPActionPerformed
        // Add your handling code here:
        Encoding.setText ("ISO2022JP");        
    }//GEN-LAST:event_ISO2022JPActionPerformed

    private void EUC_JP_LINUXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EUC_JP_LINUXActionPerformed
        // Add your handling code here:
        Encoding.setText ("EUC_JP_LINUX");        
    }//GEN-LAST:event_EUC_JP_LINUXActionPerformed

    private void EUC_JPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EUC_JPActionPerformed
        // Add your handling code here:
        Encoding.setText ("EUC_JP");        
    }//GEN-LAST:event_EUC_JPActionPerformed

    private void Cp943CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cp943CActionPerformed
        // Add your handling code here:
        Encoding.setText ("Cp943C");        
    }//GEN-LAST:event_Cp943CActionPerformed

    private void Cp943ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cp943ActionPerformed
        // Add your handling code here:
        Encoding.setText ("Cp943");        
    }//GEN-LAST:event_Cp943ActionPerformed

    private void Cp942CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cp942CActionPerformed
        // Add your handling code here:
        Encoding.setText ("Cp942C");        
    }//GEN-LAST:event_Cp942CActionPerformed

    private void Cp939ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cp939ActionPerformed
        // Add your handling code here:
        Encoding.setText ("Cp939");        
    }//GEN-LAST:event_Cp939ActionPerformed

    private void Cp33722ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cp33722ActionPerformed
        // Add your handling code here:
        Encoding.setText ("Cp33722");        
    }//GEN-LAST:event_Cp33722ActionPerformed

    private void ISO2022CN_CNSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ISO2022CN_CNSActionPerformed
        // Add your handling code here:
        Encoding.setText ("ISO2022CN_CN");        
    }//GEN-LAST:event_ISO2022CN_CNSActionPerformed

    private void EUC_TWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EUC_TWActionPerformed
        // Add your handling code here:
        Encoding.setText ("EUC_TW");        
    }//GEN-LAST:event_EUC_TWActionPerformed

    private void Cp964ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cp964ActionPerformed
        // Add your handling code here:
        Encoding.setText ("Cp964");        
    }//GEN-LAST:event_Cp964ActionPerformed

    private void Cp950ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cp950ActionPerformed
        // Add your handling code here:
        Encoding.setText ("Cp950");        
    }//GEN-LAST:event_Cp950ActionPerformed

    private void Cp948ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cp948ActionPerformed
        // Add your handling code here:
        Encoding.setText ("Cp948");        
    }//GEN-LAST:event_Cp948ActionPerformed

    private void Cp937ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cp937ActionPerformed
        // Add your handling code here:
        Encoding.setText ("Cp937");        
    }//GEN-LAST:event_Cp937ActionPerformed

    private void Big5_HKSCSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Big5_HKSCSActionPerformed
        // Add your handling code here:
        Encoding.setText ("Big5_HKSCS");        
    }//GEN-LAST:event_Big5_HKSCSActionPerformed

    private void MS936ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MS936ActionPerformed
        // Add your handling code here:
        Encoding.setText ("MS936");        
    }//GEN-LAST:event_MS936ActionPerformed

    private void ISO2022CN_GBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ISO2022CN_GBActionPerformed
        // Add your handling code here:
        Encoding.setText ("ISO2022CN_GB");        
    }//GEN-LAST:event_ISO2022CN_GBActionPerformed

    private void ISO2022CNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ISO2022CNActionPerformed
        // Add your handling code here:
        Encoding.setText ("ISO2022CN"); 
    }//GEN-LAST:event_ISO2022CNActionPerformed

    private void GBKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GBKActionPerformed
        // Add your handling code here:
        Encoding.setText ("GBK");        
    }//GEN-LAST:event_GBKActionPerformed

    private void EUC_CNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EUC_CNActionPerformed
        // Add your handling code here:
        Encoding.setText ("EUC_CN");        
    }//GEN-LAST:event_EUC_CNActionPerformed

    private void Cp935ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cp935ActionPerformed
        // Add your handling code here:
        Encoding.setText ("Cp935");        
    }//GEN-LAST:event_Cp935ActionPerformed

    private void AboutItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AboutItemActionPerformed
        // Add your handling code here:
        StatusBar.setText ("Version " + version + "\tCopyright (C) 2004, ChiWai.");        
    }//GEN-LAST:event_AboutItemActionPerformed

    private void Cp942ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cp942ActionPerformed
        // Add your handling code here:
        Encoding.setText ("Cp942");
    }//GEN-LAST:event_Cp942ActionPerformed

    private void Cp930ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cp930ActionPerformed
        // Add your handling code here:
        Encoding.setText ("Cp930");        
    }//GEN-LAST:event_Cp930ActionPerformed

    private void MS1381ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MS1381ActionPerformed
        // Add your handling code here:
        Encoding.setText ("MS1381");        
    }//GEN-LAST:event_MS1381ActionPerformed

    private void MS950ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MS950ActionPerformed
        // Add your handling code here:
        Encoding.setText ("MS950");        
    }//GEN-LAST:event_MS950ActionPerformed

    private void DefaultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DefaultActionPerformed
        // Add your handling code here:
        Encoding.setText (System.getProperty ("file.encoding"));
    }//GEN-LAST:event_DefaultActionPerformed

    private void Big5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Big5ActionPerformed
        // Add your handling code here:
        Encoding.setText ("Big5");
    }//GEN-LAST:event_Big5ActionPerformed

    private void BrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BrowseActionPerformed
        // Add your handling code here:
        JFileChooser SelectPath = new JFileChooser();
        SelectPath.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        SelectPath.setMultiSelectionEnabled(true);
        SelectPath.setDialogType(JFileChooser.OPEN_DIALOG);
        SelectPath.setFileFilter(new PacketFilter());
        SelectPath.setDialogTitle("Select a folder");
          
        if (SelectPath.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            //Add selected files to the folder list
            AddFolder(FolderList, SelectPath.getSelectedFiles());           
        }        


        //Enable "Convert" if there is folder in the list
        if (FolderList.getItemCount() != 0) {
            Convert.setEnabled(true);
        }        

    }//GEN-LAST:event_BrowseActionPerformed
    

    /*
     * Add files to the list
     *
     * @parm FolderList List to store the files
     * @parm Files Files to store to the list
     */
    private void AddFolder (java.awt.List FolderList, java.io.File[] Files) {            
        int FolderListItemCount = FolderList.getItemCount();                    
        for (int i = 0; i < Files.length; i++) {            
            if (FolderListItemCount == 0 ) {            
                //If there is no items, add selected files to the list                
                FolderList.add (Files[i].getAbsolutePath());
            } else {            
                int j;                
                //Add only if there is no duplicated file                
                for (j = 0; j < FolderListItemCount; j++) {                
                    if (FolderList.getItem(j).compareToIgnoreCase(Files[i].getAbsolutePath()) == 0) {                                                                
                        break;                                             
                    }                    
                }

                
                if (j == FolderListItemCount) {                
                    FolderList.add (Files[i].getAbsolutePath());                  
                }                
            }            
        }
        
        if (FolderListItemCount < FolderList.getItemCount()) {
            //Update status bar
            StatusBar.setText ("Files/folders are added to the list.");
        }
    }
    private void FolderListItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_FolderListItemStateChanged
        // Add your handling code here:
        if (FolderList.getSelectedIndexes().length  > 0 ) {
            Remove.setEnabled(true);
        } else {
            Remove.setEnabled(false);
        }                
    }//GEN-LAST:event_FolderListItemStateChanged
    
    private void RemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveActionPerformed
        // Add your handling code here:
        //Remove all selected item(s)
        while (FolderList.getSelectedIndexes().length > 0) {
            FolderList.remove(FolderList.getSelectedIndexes()[0]);
        }
        
        //Disable Remove button as there is no item
        Remove.setEnabled(false);
        
        //Disable Convert button if there is no item
        if (FolderList.getItemCount() == 0) {
            Convert.setEnabled (false);
        }
        
        //Update status
        StatusBar.setText ("Files/folders are removed.");
        
    }//GEN-LAST:event_RemoveActionPerformed
        
    private void ConvertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConvertActionPerformed
        // Add your handling code here:        
        System.out.println ("Start converting using encoding " + Encoding.getText());
        
        //Call function to convert
        for (int i = 0; i < FolderList.getItemCount(); i++) {                
            ID3Convert (new File(FolderList.getItem(i)), RecursiveCheckBox.isSelected(), Encoding.getText());
        }
        
        UpdateStatus (nbFolder, nbProcessed, nbConverted);
             
        //Remove the folder list
        while (FolderList.getItemCount() > 0) {
            FolderList.remove(0);
        }
        
        
        //Disable Convert button as there is no folder list
        Convert.setEnabled(false);
        
        //Reset the statistics
        nbFolder = 0;
        nbProcessed = 0;
        nbConverted = 0;

        System.out.println ("Finish conversion.");
    }//GEN-LAST:event_ConvertActionPerformed
    
    
    private void QuitApp () {
        System.out.println ("Bye bye!");
        System.exit(0);        
    }
    
    private void QuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuitActionPerformed
        // Add your handling code here:
        QuitApp();
    }//GEN-LAST:event_QuitActionPerformed
    
    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        QuitApp();
    }//GEN-LAST:event_exitForm
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {  
        if (args.length == 0) {             
             //Run in graphical mode
             new UnicodeRewriter().show();
         } else {
             //Run in command line mode
             ID3iconv.main (args);
         }
    }
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AboutItem;
    private javax.swing.JMenu AboutMenu;
    private javax.swing.JMenu Arabic;
    private javax.swing.JMenu Baltic;
    private javax.swing.JMenuItem Big5;
    private javax.swing.JMenuItem Big5_HKSCS;
    private javax.swing.JButton Browse;
    private javax.swing.JMenu CEuropean;
    private javax.swing.JMenu Chinese;
    private javax.swing.JButton Convert;
    private javax.swing.JMenuItem Cp1026;
    private javax.swing.JMenuItem Cp1046;
    private javax.swing.JMenuItem Cp1097;
    private javax.swing.JMenuItem Cp1098;
    private javax.swing.JMenuItem Cp1123;
    private javax.swing.JMenuItem Cp1124;
    private javax.swing.JMenuItem Cp1250;
    private javax.swing.JMenuItem Cp1251;
    private javax.swing.JMenuItem Cp1253;
    private javax.swing.JMenuItem Cp1254;
    private javax.swing.JMenuItem Cp1255;
    private javax.swing.JMenuItem Cp1256;
    private javax.swing.JMenuItem Cp1258;
    private javax.swing.JMenuItem Cp33722;
    private javax.swing.JMenuItem Cp420;
    private javax.swing.JMenuItem Cp424;
    private javax.swing.JMenuItem Cp71257;
    private javax.swing.JMenuItem Cp737;
    private javax.swing.JMenuItem Cp775;
    private javax.swing.JMenuItem Cp838;
    private javax.swing.JMenuItem Cp852;
    private javax.swing.JMenuItem Cp855;
    private javax.swing.JMenuItem Cp856;
    private javax.swing.JMenuItem Cp857;
    private javax.swing.JMenuItem Cp861;
    private javax.swing.JMenuItem Cp862;
    private javax.swing.JMenuItem Cp864;
    private javax.swing.JMenuItem Cp865;
    private javax.swing.JMenuItem Cp866;
    private javax.swing.JMenuItem Cp869;
    private javax.swing.JMenuItem Cp871;
    private javax.swing.JMenuItem Cp874;
    private javax.swing.JMenuItem Cp875;
    private javax.swing.JMenuItem Cp930;
    private javax.swing.JMenuItem Cp933;
    private javax.swing.JMenuItem Cp935;
    private javax.swing.JMenuItem Cp937;
    private javax.swing.JMenuItem Cp939;
    private javax.swing.JMenuItem Cp942;
    private javax.swing.JMenuItem Cp942C;
    private javax.swing.JMenuItem Cp943;
    private javax.swing.JMenuItem Cp943C;
    private javax.swing.JMenuItem Cp948;
    private javax.swing.JMenuItem Cp949;
    private javax.swing.JMenuItem Cp949C;
    private javax.swing.JMenuItem Cp950;
    private javax.swing.JMenuItem Cp964;
    private javax.swing.JMenuItem Cp970;
    private javax.swing.JMenu Cyrillic;
    private javax.swing.JMenuItem Default;
    private javax.swing.JLabel DropPad;
    private javax.swing.JMenu EEurope;
    private javax.swing.JMenu EEuropean;
    private javax.swing.JMenuItem EUC_CN;
    private javax.swing.JMenuItem EUC_JP;
    private javax.swing.JMenuItem EUC_JP_LINUX;
    private javax.swing.JMenuItem EUC_KR;
    private javax.swing.JMenuItem EUC_TW;
    private javax.swing.JMenu EastAsia;
    private javax.swing.JTextField Encoding;
    private javax.swing.JLabel EncodingLabel;
    private javax.swing.JMenu EncodingMenu;
    private javax.swing.JMenu Farsi;
    private java.awt.List FolderList;
    private javax.swing.JMenuItem GBK;
    private javax.swing.JMenu Greek;
    private javax.swing.JMenu Hebrew;
    private javax.swing.JMenuItem ISO2022CN;
    private javax.swing.JMenuItem ISO2022CN_CNS;
    private javax.swing.JMenuItem ISO2022CN_GB;
    private javax.swing.JMenuItem ISO2022JP;
    private javax.swing.JMenuItem ISO8859_5;
    private javax.swing.JMenuItem ISO8859_6;
    private javax.swing.JMenuItem ISO8859_7;
    private javax.swing.JMenuItem ISO8859_8;
    private javax.swing.JMenu Icelandic;
    private javax.swing.JMenuItem JIS0201;
    private javax.swing.JMenuItem JIS0208;
    private javax.swing.JMenuItem JIS0212;
    private javax.swing.JMenuItem JISAutoDetect;
    private javax.swing.JMenu Japanese;
    private javax.swing.JMenuItem Johab;
    private javax.swing.JMenuItem KOI8_R;
    private javax.swing.JMenu Korean;
    private javax.swing.JMenuItem MS1381;
    private javax.swing.JMenuItem MS874;
    private javax.swing.JMenuItem MS932;
    private javax.swing.JMenuItem MS936;
    private javax.swing.JMenuItem MS949;
    private javax.swing.JMenuItem MS950;
    private javax.swing.JMenuItem MacArabic;
    private javax.swing.JMenuItem MacCentral;
    private javax.swing.JMenuItem MacCyrillic;
    private javax.swing.JMenuItem MacGreek;
    private javax.swing.JMenuItem MacHebrew;
    private javax.swing.JMenuItem MacIceland;
    private javax.swing.JMenuItem MacRoman;
    private javax.swing.JMenuItem MacRomania;
    private javax.swing.JMenuItem MacThai;
    private javax.swing.JMenuItem MacTurkish;
    private javax.swing.JMenuItem MacUkraine;
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JMenu MiddleEast;
    private javax.swing.JMenu Nordic;
    private javax.swing.JButton Quit;
    private javax.swing.JCheckBox RecursiveCheckBox;
    private javax.swing.JButton Remove;
    private javax.swing.JMenu Roman;
    private javax.swing.JMenu Romania;
    private javax.swing.JMenu Russian;
    private javax.swing.JMenu SESWAsia;
    private javax.swing.JMenuItem SJIS;
    private javax.swing.JMenu Simplified;
    private javax.swing.JLabel StatusBar;
    private javax.swing.JMenuItem TIS620;
    private javax.swing.JMenu Thai;
    private javax.swing.JMenu Traditional;
    private javax.swing.JMenu Turkish;
    private javax.swing.JMenu Ukraine;
    private javax.swing.JMenu Vietnamese;
    private javax.swing.JMenu WEurope;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
    private ID3iconv ID3Rewriter;//Use ZhouFeng's library to convert ID3 tags
    private int nbFolder;//Number of processed folders
    private int nbProcessed;//Number of processed files
    private int nbConverted;//Number of converted files
    private String version;//Version of this software

    
    
    /**Convert MP3 files in Folder to use Unicode ID3 tags
     * @param Folder Files in Folder will be converted
     * @param Recursive Access the folder recurively
     * @param Encoding Encoding for the source
     * 
     */
    private void ID3Convert (File Folder, boolean Recursive, String Encoding) {
        if (Folder.canRead() && Folder.canWrite()) {
            if (Folder.isFile()) {
                if (Folder.getName().toLowerCase().endsWith(".mp3") ) {             
                    System.out.println ("Converting..." + Folder.getAbsoluteFile());       
                    nbProcessed++;           
                    try {
                        if (ID3Rewriter.convert (Folder, Encoding) == 0) {                                                            
                            nbConverted++;                                                        
                        }                                            
                    } catch (Exception e) {                                                
                        System.err.println ("Error " + e.getMessage());                                                                         
                    }
                }        
            } else {            
                System.out.println (Folder.getAbsoluteFile() + " is a folder");                        
                nbFolder++;                
                if (Recursive == true) {                
                    //Recursivly convert files in this folder
                    try {
                        for (int j = 0; j < Folder.list().length; j++) {                        
                            ID3Convert (Folder.listFiles()[j], Recursive, Encoding);                    
                        }            
                    } catch (Exception e) {
                        System.err.println ("Error " + e.getMessage());
                    }
                }
            }
        } else {
            System.err.println ("Cannot read and write " + Folder.getName());            
        }
    }
   
      
    /**Display the status of the conversion
     * @param folder Number of processed folders
     * @param processed Number of processed files
     * @param converted Number of converted files
     *
     * 
     */
    private void UpdateStatus (int folder, int processed, int converted) {
        StatusBar.setText("Processed: " + processed + " files in " + folder +" folders. Converted: " + converted + " files.");
    }

}
